### ISSUE TITLE
12 kingdoms in egypt doesnt turn in after marion is finished

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#110]
i just finished marion, now i want hathor for my eggys. but i cant turn in the completion of the 12 kingdoms to get her. must be a bug right ?

**Comment by Ryddag** [comment]
I have fixed your save, you missed some hidden quest giver like "CyprusFlagPaphos" in it.
This was due to the bug introduced yesterday (#101) with the first server update (fix inventory) and fixed later. In mean time i know you does another 12K quest just before the second server update, so this one don't have add you the correct "cyprusflag" for this quest.

Any way it's fixed, tell me if not.
If any one has also this issue pm on discord.

**Comment by Ryddag** [comment]
I did the same fix for other player it seem to work so i close this issue.
