### ISSUE TITLE
island of king tuk 

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#142]
in the ambrosia project - the island of king tuk when u have to tribute 600 food to summon the big ass boor. u cant kill him, i had 10 towers all firing super damage at him and he didnt take any dmg at all., if u cant kill him, u cant get the treasure, no treasure no ambrosia project. please make him killable !

**Comment by PF2K** [comment]
I've done that quest twice already with no problems. (With Persia, that is)

**Comment by jiffyette** [comment]
greek here

**Comment by musictopia** [comment]
The problem is they gave him so much pierce damage that you can't kill him from arrows.  The original game was set up like that to keep from chasing him around your town center and then your town center can kill him.  I hope they fix it.  Because it is frustrating if a person can't even use guard towers or archers to kill him.

**Comment by IamMidas** [comment]
i killed him as greek without any problems

**Comment by jiffyette** [comment]
how

**Comment by doddianca** [comment]
We used to line the fence with towers, and then use bowmen or any arrow carrier to kill it.

**Comment by jiffyette** [comment]
thats exactly what i did, and he proceeded to destroy all i had in front of him, towers tc, and infantry

**Comment by Ryddag** [comment]
So bug or not ?

**Comment by musictopia** [comment]
In the original game, players would send king tusk running around the town center so the town center could kill him.  They fixed that by not allowing any arrows to kill him.  Obviously this causes another problem because if players use guard towers, they will still lose though.  The easy fix would be to take out the part where king tusk has tons of pierce armor.

**Comment by Ryddag** [comment]
So if it was an choice from original dev i will keep this like it is.

**Comment by musictopia** [comment]
When I mentioned the issue where I even used consumables that did not help, they said that if the game had kept going, they would figure out another way to keep somebody from using the town centers from destroying the general but still allowing other archers to destroy it for cases where somebody used guard towers or archer units.  However, since the game got shut down, they could not do anything more.
