### ISSUE TITLE
mosaic tile daily glitch

### ISSUE THREAD

**Issue by elrawen** [ProjectCeleste/Celeste_Server#151]
if you move your units further away so after the next trade port you will keep this those units i don't think this is intented and believe this is an old glitch since it's trigger wise i suppose

**Comment by jiffyette** [comment]
havent had this

**Comment by elrawen** [comment]
Well it's a rare one but it's possible to glitch it out

**Comment by musictopia** [comment]
I don't think its a bug.  I think somebody should be able to keep the units after getting to the next port.  So it can make it easier anyways.

**Comment by elrawen** [comment]
Well i had double speed from the new port and 2 tiremes from the previous port

**Comment by Axel231** [comment]
I dont think it really matters, its an easy quest with or without the "extra" units

maybe someone who is 100% sure it was like that can chime in, but I'd prefer it stayed the way it is now

**Comment by Wobling** [comment]
I noticed this too.

**Comment by jiffyette** [comment]
i found i got 9 out of 10 ports. then the 10th wouldnt trigger

**Comment by doddianca** [comment]
I run this quest twice a day, and yes you can keep your prior units before you visit the dock.  This just means that if you have a good ship with you, you can do something into the next frame if you have time to spare.  Though with strategy aka "distraction" you can get past the enemy units without issue.  And don't forget if the merchant ship is damaged it can be fixed with fishing boats.

**Comment by Ryddag** [comment]
this glitch was also on original game, and i think it not really important to fix this.
