### ISSUE TITLE
Request: pages on Mail.

### ISSUE THREAD

**Issue by ChewierElf** [ProjectCeleste/Celeste_Server#170]
I've noticed that there are only 2 pages, each with 5 mail slots. I might be wrong but my memory tells me that there were 4 pages max. Would it be possible if I remember correctly of course, to extend the mail with 2 more pages? 
Also when looking at expiration date, again I thought that was 1 month (aka 30 days) seems to be a fortnight (14 days) Likewise is it possible to extend if that was the original design?

**Comment by Ryddag** [comment]
Actually limited to 10 because i don't want you to use this as storage, same for exp. date.
Also for me it seem better like this, prevent user to keep cod letter too long much without accept them and block the item too long.

Note: don't worry about cod return (coin or stuff if declined), even if you have more than 10 mail you will still receive them.
