### ISSUE TITLE
Bug in quest Run the blocakde

### ISSUE THREAD

**Issue by Jole1** [ProjectCeleste/Celeste_Server#190]
There are two islands in this quest.. in first there is no town center, only start buildings

**Comment by musictopia** [comment]
I played run the blockade with no problems.  I guess it could be problems where there was objects in the way.  Even on project penelope, I noticed sometimes, the same thing would happen when it would load the scenario.  For now, just start the quest again.  I doubt they can keep the problem from happening since it only happens once in a while.

**Comment by Ryddag** [comment]
Someone have retried it since ?

**Comment by musictopia** [comment]
I have retried today and had no problems with Run The Blockade.
