### ISSUE TITLE
Epic Recipe Production Resets

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#225]
When you leave a civ, and enter another civ., the epic materials being produced reset back to the 6hr mark.  If left alone for 12 hrs you will get 2 items, but if you flip back to a civ after log out, then resets itself.  May include some rare recipes also doing this, and not all civs are doing it.  ie: Greek my gold recipe seems fine, but in Egypt the Obsidian blocks resets, in Persia my guyanna planks reset.

**Comment by doddianca** [comment]
Seems to happen if in one civ and you visit a realm and do questing once you hit the Return To Capital button, the shops reset some of the timers.  This may need to be tested out by others but that was what I noticed last night.

**Comment by fabsroman** [comment]
I am having the same issue. However, this morning, after leaving the game off for 8 hours, the problem was across all civs and it happens in Babylon with my farmers workshops producing grain. So, I have seen it with workshops producing epic advanced, epic standard, rare standard, and common standard materials.

I tried packing up all the standard workshops and then rebuilding them, but that did not work. Trying to figure out some reason or pattern behind this, but I have not been able to figure it out.
