### ISSUE TITLE
No EP from The Defense of Crete

### ISSUE THREAD

**Issue by KiBlob** [ProjectCeleste/Celeste_Server#235]
The Defense of Crete repeatable quest no longer award EP after the latest patch.
Reward for difficulty hard, challenge and impossible are the same.

**Comment by Ryddag** [comment]
About reward this was already like this in original game (only lvl scale for rewards and the amount only change when you change num of waves).
About EP is was us who add EP to the "custom Crete quests", and we will not re-add them for the original mode since we can't make them scall to the difficulty lvl.

**Comment by KiBlob** [comment]
About EP, I think that once said that you changed all Alliance Points to EP until you fix alliance war. A suggestion is that instead of removing it completely to reward only the lowest (8 EP) for all difficulty level.
