### ISSUE TITLE
Very bad loot with Elite quests.

### ISSUE THREAD

**Issue by M3SUT85** [ProjectCeleste/Celeste_Server#257]
Hi there, 
I have been playing this game since closed beta. I have noticed that after the recent major patch we had to the loot table, the drops from elite quests are pretty bad. The drops consist of mainly uncommon and rare stuffs which is no good to someone at level 40, and epics are very few. Legendary gear is almost non existent from elite quests. I can confirm that this was not the case in the original game back in the day. Epic gear used to drop more frequently and there was a chance to drop legendary gear also. It is sad because right now the only thing really worth playing for a level 40 civ is legendary quests. Elite quest is basically a waste of time as the drops are useless. I don't think it is just "bad luck" because a lot of people seem to agree that they are actually pretty bad. I tested it by playing back to back all of the 12 Kingdoms elite recaps, and also few Argos elites, and the loot consisted of uncommon and rare stuffs, no epics or legendary gear. My coop partner also had the same result. 

It has been a while since that major update to loot tables, and we have had enough time to test it out. It would be appropriate a poll was taken to see what people think of this situation and act on it accordingly.
Thank you

**Comment by PharosAvaris** [comment]
I dont rly play much 12 Kingdoms elite recaps or Argos elites but i used to play lots of Elite babylonian booster quests and can confirm that "the drops from elite quests are pretty bad. The drops consist of mainly uncommon and rare stuffs which is no good to someone at level 40, and epics are very few." cant say better then this..
We whould appreciate it if u will reconsider drop rate for elite quests...

**Comment by musictopia** [comment]
I edited the quest tables last time.  The bad news is I have no way of knowing exactly what the old loot tables was.  Before the last improvement, the loot tables was worse.  I do know for sure the loot tables for elite and regular was exactly the same.  The only difference is the elite gets more chests, coin and empire points.  It would probably be easy to have new loot tables however, its up to the developers if they decide to do it or not.

**Comment by Mayureshete** [comment]
In a sense i agree, i use to get legendary for every 10 elite quest on aveage, but since 2 weeks almost even epic drops are rare

**Comment by musictopia** [comment]
I do know for sure the drop rates has not changed in over 2 months.

**Comment by Hidannie** [comment]
I am with you mesut85. I think possiblies on elite or leg quests must be increased. I opened lots of chests that level 40 (and %40-50 of from elite/leg quests). But drops are: %80 uncommon and trashes.

**Comment by Bircangelo** [comment]
Very bad? It is an abomination, i did a lot of elite quests and got a lot chests but i didn't open them till there was many, but in the end what did i get? 3 epics and not a single legendary...i mean...are you serious?

**Comment by Lyris2000** [comment]
very bad loot not only elite quests also legendarys not giving anything good makes me boring to play them again ,spending 1 hour in marion to get green stuff,i dont think this will help the community to grow rather it makes players not want to play the game ,consider that

**Comment by KevinW1998** [comment]
Okay, fair, elite quests loot do need improvements...

But telling me that legendaries giving bad loot is just false... I mean, questgiver chest do not even drop uncommon stuff... I feel like you guys only expect legendaries all the time, **consider that**

**Comment by Lyris2000** [comment]
well ill explain you again because you dont want to understand ,played ten times new leg quests got crap makes me boring to playthem again and get the same CRAP AGAIN ,because they take too long to complete and alot of effort ,and people dont have all the free time in the world to play aoeo all day, its agame and youre supposed to have fun not getting bored ,thats what im saying and if i feel that way probably other players feel the same and if we want tomake a bigger community with many players its supposed to be fun and not boring and frustrating

**Comment by Bircangelo** [comment]
After doing the new legendaries i have to agree with lyris, i got more old legendaries then the new ones(even the old ones drop chance is bad if you compare the difficulty)When it become free for all i heard from the champion supporters the drop rate has been reduced by that update, which is understandable if the drop rate was riddiciculsly high, but thenew drop rate for athens is really bad for legendaries ,i think too, just my opinion though.So instead of changing the drop rate for athens , how about stopping the old legendaries to drop in athens instead?So whenever we get legendaries in athens we can be sure its the athens one.Just a suggestion.

**Comment by M3SUT85** [comment]
I agree with Bircangelo, drop rates from Athens quests is pretty bad too compared to the difficulty and the time it consumes. I agree with Athens only dropping Athens gear and not the old legendary gear, considering you can't get Athens gear in the old legendary quests. The loot chance for the new legendary gear is very slim this way and I think it needs to be better.

**Comment by Kenjn** [comment]
I agree the loot ugh ,Boring as **** I play alot of leg quest and leg quest take an hour to finsh and barely you get EPIC items barely, All of it Rare and uncommon and i'm not gonna gear my self with rare items and believe me a lot of people will get bored when they do leg and get nothing , idk
