### ISSUE TITLE
Baby Steps to the Throne not completing 

### ISSUE THREAD

**Issue by PF2K** [ProjectCeleste/Celeste_Server#28]
For some reason, "Town Center Must Survive" doesn't get triggered by the end of the mission and you are unable to complete the quest. It's happened to more than one person so far.

**Comment by musictopia** [comment]
I think it could still be an issue where if somebody accepts the quest but completes it when they log in, it has the problem.  That bug seems to be fixed for all other quests but not this one apparently.  When I did the quest, I think the reason I did not come across it was because I was able to do more than one quest in a session including that one.

**Comment by IamMidas** [comment]
i think i did it by killing the enemys

**Comment by IamMidas** [comment]
but i had that too

**Comment by Ryddag** [comment]
If you have accepted this quest before the last update, you have to dismiss it
