### ISSUE TITLE
Drop rate in Moes and Elite quests is terrible

### ISSUE THREAD

**Issue by DaHoMs** [ProjectCeleste/Celeste_Server#297]
Only good drop rate is in Athens legendary guests

**Comment by KevinW1998** [comment]
In elite quests I agree... but in moes we have the quality drop rates not too high so we don't get into inflation.

**Comment by Ryddag** [comment]
"Only good drop rate is in Athens legendary guests" wrong its all legendary quest, it the same rate has classic leg too.

Also elite have same drop rate a standard quest, but you get more chest with elite quest (or chest level 40 instead of 37) than regular. That the only change between standard quest and elite one.
