### ISSUE TITLE
General store Troy not working

### ISSUE THREAD

**Issue by onlinemindgem** [ProjectCeleste/Celeste_Server#33]
General store Troy not working

See:

http://imgur.com/a/OUlpR

**Comment by Ryddag** [comment]
Not working all time, or logoff login fix it ?

**Comment by musictopia** [comment]
Not working all the time.

**Comment by Ryddag** [comment]
I found the cause, this affect store who are the seem and exist in different region, this store is actually the same as in your capital city.

**Comment by BOSAIF86** [comment]
I have somewhat similar issue, it happened to me when I moved the General Store to another location; however, I got multiple stores lol. My scenario was like:
- Firstly, I packed the general store into a blue print, built it somewhere else.
- I built a Mostoragorium building on the location where the general store was.
- I started a quest, finished, returned to my home town then I saw a NEW general store located beneath the Mostoragorium building!!
- I had to move the Mostoragorium building in order to move the general store building; I packed the NEWLY appeared general store building to a blueprint.
- I left the place where the general store originally was located empty.
- I started another quest and returned back, I found another NEW general store built back lol, I left it be as it is and built the previously built and the old one beside each other.

Please check the image I uploaded. Each time one of them work and the other stuck empty!

[http://imgur.com/a/Vp96N](url)

**Comment by Ryddag** [comment]
@BOSAIF86 #70
