### ISSUE TITLE
Capital City with bug buildings 

### ISSUE THREAD

**Issue by Messiah360** [ProjectCeleste/Celeste_Server#70]
This could be happen when you move your general store and mail building. After log off and log in, you will have more of that buildings. For now I have 3 general stores and 3 mail buildings ...

**Comment by Ryddag** [comment]
have you pack them to bp before move them or just move ?

**Comment by Messiah360** [comment]
Packed and them place. Log off and then back and I was 2 of those buildings too near of each other

**Comment by Ryddag** [comment]
ok that why, we know the issue only this two building produce it, because their are a part of original scenario file, and their the only packable to bp.
In fact we don't find out yet how to destroy proprelly scn building

**Comment by BOSAIF86** [comment]
I have somewhat similar issue, it happened to me when I moved the General Store to another location; however, I got multiple stores lol. My scenario was like:
Firstly, I packed the general store into a blue print, built it somewhere else.
I built a Mostoragorium building on the location where the general store was located.
I started a quest, finished, returned to my home town then I saw a NEW general store located beneath the Mostoragorium building!!
I had to move the Mostoragorium building in order to move the general store building; I packed the NEWLY appeared general store building to a blueprint.
I left the place where the general store originally was located empty.
I started another quest, returned back, I found another NEW general store appeared again lol, I left it be as it is and built the previously built/appeared and the old one beside each other.
Please check the image I uploaded. Each time one of them work and the other stuck empty!
http://imgur.com/a/Vp96N
