### ISSUE TITLE
Marcus Pollux Rewards bugged

### ISSUE THREAD

**Issue by Messiah360** [ProjectCeleste/Celeste_Server#89]
It appears you can only get this one time, if you deleted your capital city and create a new one you can collect all of them ...

**Comment by Ryddag** [comment]
? Don't understand what you means

**Comment by Messiah360** [comment]
Marcus Pollux rewards like the garden and sculpture stores can be redeem ... only one time. (Greeks) If you delete your capital and start over, that rewards can be redeem, are buged

**Comment by musictopia** [comment]
I don't see the problem.  Even in the original game, if somebody deleted the capital city they can get the rewards again because the player is starting over.  I think it would be bad if somebody already collected the rewards to not be able to collect again because the player decided to start over again.

**Comment by Ryddag** [comment]
Yep its has to be like this
